# Please read this carefully
# Each mandatory section will be marked
# With a comment stating "MANDATORY"
# If an item which has sub items is marked MANDATORY, please fill out all subsections within
# unless marked otherwise
# Please fill out all mandatory sections
# Plese fill out all blank sections that you find necessary
# Note that some files have some information provided in the template
# This information should not be changed

# MANDATORY
apiVersion: #apps/v1

# MANDATORY
kind: Deployment

# MANDATORY
metadata:
  name:
  # the following is an optional field where we can have users speicify the namespace that they want to use
  # NOTE: the namespace will be `default` if it's not speificed in the yaml
  namespace: default

# MANDATORY
spec:
  selector:
    matchLabels:
      app:
      tier:
      # role:

  replicas:

  template:
    metadata:
      labels:
        app:
        tier:
        # role:

    spec:
      containers:
      - name:
        image:
        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu:
            memory:
        
        # NOT MANDATORY 
        # please uncomment for use
        #env:
        #- name:
        #  value:
        #  
        #  ports:
        #  - containerPort: