#Please read this carefully
# Each mandatory section will be marked
# With a comment stating "MANDATORY"
# If an item which has sub items is marked MANDATORY, please fill out all subsections within
# unless marked otherwise
# Please fill out all mandatory sections
# Plese fill out all blank sections that you find necessary
# Note that some files have some information provided in the template
# This information should not be changed

# MANDATORY
apiVersion: apps/v1

# MANDATORY
kind: Deployment

# MANDATORY
metadata:
  name: myAppDeploy
  namespace: myAppDeploy-42069

# MANDATORY
spec:
  selector:
    matchLabels:
      app: myApp
      # tier: 
      # role:

  replicas: 10

  template:
    metadata:
      labels:
        app: myApp
        # tier:
        # role:

    spec:
      containers:
      - name: myContainer
        image: markser/myDockerImageExample:latest
        imagePullPolicy: IfNotPresent

        # NOT MANDATORY
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
        
        # NOT MANDATORY 
        # please uncomment for use
        #env:
        #- name:
        #  value:
        #  
        ports:
        - containerPort: 8080